API Gateway pull request
agrudkow/apsi-bug-tracker pull request #6
Opened 2021-11-17 14:46 UTC by malwro

2021-11-20 22:35 UTC, agrudkow requested changes

2021-11-20 22:35 UTC, agrudkow commented on lambda/handler.py
> +    sys.exit()
chyba lepszym pomysłem jest zwrócenie erroru (z kodem 500) w postaci request niż sys.exit

2021-11-20 22:35 UTC, agrudkow commented on lambda/handler.py
> +        cur.execute("select * from zgloszenia")
w sumie to wrzucił bym to do innej lambdy, który bo póki co odpowiadała za insertowanie

2021-11-20 22:35 UTC, agrudkow commented on lambda/handler.py
> +import pymysql
coś mi tu nie gra, `pymysql` nie jest defautową biblioteką, zatem powinna być doinstalowana a nigdzie nie widzę pliku z pliku z bibliotekami (w example użyłem standardowego podejścia venv + requirements). Także czy ta lambda wgl działa na AWS jesli nie ma nigdzie zdefiniowanej tej biblioteki? Dodatkowo w związku z potrzebą doinstalowywania dodatkowych bibliotek nie powinniśmy używać rozwiązań typu wspomniany `venv`?

2021-11-20 22:35 UTC, agrudkow commented on lambda/handler.py
> +import time
to chyba nie jest nigdzie używane 😉

2021-11-20 22:35 UTC, agrudkow commented on lambda/handler.py
> +        'body' : records
generalnie jest trochę "problemów" z formatowaniem kodu i trzeba się na coś umówić tj. na jakąś wspólną konfigurację. W przykładowej lambdzie używałem `yapf` do formatowania kodu i kilka innych bibliotek przydatnych podczas developmentu (są one widoczne w pliku `requirements-dev.txt`.

2021-11-20 22:35 UTC, agrudkow commented on lib/apsi-bug-tracker-stack.ts
> +    const getAllIssuesRoute = apiGateway.root.addResource('zgloszenia');
trzymałbym się polskich ścieżek. Dodatkowo definiował bym gdzieś (np. zrobić folder `utils` a w nim plik `routes.ts`) enum-a, w którym są ścieżki zdefiniowane (patrz projekt z frontend-em)

2021-11-20 23:13 UTC, malwro commented on lambda/handler.py
> +        cur.execute("select * from zgloszenia")
Proszę, żebyś sprecyzował swój komentarz, jest w nim jakiś błąd

2021-11-21 09:41 UTC, agrudkow commented on lambda/handler.py
> +        cur.execute("select * from zgloszenia")
Faktycznie brzmi to mało sensownie xd, ale w ogólności chodziło mi o wyniesienie tego (tej funkcjonalności) do innej lambdy. Aczkolwiek, już zaadresowałaś tą kwestię, a ja zapomniałem, że o tym mówiłaś tj. że później to się wyniesie do innej lambdy

2022-01-03 09:08 UTC, closed without merging